# Kevin Moye, Complete
# This program accepts 10 integers and a number to compare from the user,
# and displays the original list, the comparison number, and a list of numbers greater than the comparison number.

def display_larger(numbers, compare_num):
   # Compares the numbers generated by user in list numbers and stores the numbers that are greater than the comparison number into a new
   # list called larger_numbers
    larger_numbers = []
    for num in numbers:
        if num > compare_num:
            larger_numbers.append(num)

    print("Original list:", numbers)
    print("Comparison number:", compare_num)
    print("Numbers greater than comparison numer:", larger_numbers)

def main():
    # Initializes a list, numbers, that will be filled with 10 user generated numbers. User then gets asked to select a number that
    # the list will be compared against. Both list and comparison number are passed to display_larger function
    numbers = []

    print ("Please enter a list of 10 integers")
    for index in range(10):
        num = int(input(f"Enter integer {index+1}: "))
        numbers.append(num)

    compare = int(input("Enter the number you wish to test if the list elements are greater than: "))

    display_larger(numbers, compare)


main()